package ld38;

import katsu.K;

import java.util.ArrayList;

/**
 * Created by shaun on 22/04/2017.
 */
public class TrollNamer {

    private static TrollNamer _instance;

    private ArrayList<String> availableNames = new ArrayList<String>();

    public TrollNamer() {
        generateNames();
    }

    private void generateNames() {

        // Names generated by http://www.rinkworks.com/namegen/fnames.cgi?d=1&f=0
        String lines[] = K.resource.loadText("random-troll-names.txt").split("\\r?\\n");

        for (String line : lines) {
            availableNames.add(line);
        }

    }

    public static TrollNamer instance() {
        if (_instance == null) {
            _instance = new TrollNamer();
        }
        return _instance;
    }

    public String nextName() {
        int pick = K.random.nextInt(availableNames.size());
        String result = availableNames.get(pick);
        availableNames.remove(pick);
        return result;
    }
}
